global:
    scrape_interval: 1m

scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 1m
      static_configs:
      - targets: ["localhost:9090"]

    - job_name: "node"
      static_configs:
      - targets: ["node-exporter:9100"]

    - job_name: "pfsense"
      scrape_timeout: 15s
      static_configs:
      - targets: ["192.168.2.1:9100"]

remote_write:
    - url: "http://192.168.2.200:3000"
      basic_auth:
        username: "USER"
        password: "PASS"


